import './globals.css';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {GoogleAnalytics} from './components/analytics';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<GoogleAnalytics ga_id={process.env.G_ANALYTICS || ''} />
				{children}
			</body>
		</html>
	);
}
